services:
  - type: web
    name: two-coats 
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && gunicorn TwoCoats.src.app:app --bind 0.0.0.0:$PORT

    envVars:
      - key: POSTGRES_URI
        sync: false
      - key: API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.9
